name: Deploy to SiteGround

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Set up SSH with passphrase
      env:
        SSH_PASSPHRASE: ${{ secrets.SG_PASSWORD }}
        SSH_PRIVATE_KEY: ${{ secrets.SG_SSH_PRIVATE_KEY }}
      run: |
        # Start the SSH agent
        eval $(ssh-agent -s)
        
        # Create the SSH_ASKPASS script to provide the passphrase
        echo "echo $SSH_PASSPHRASE" > ~/.ssh_askpass && chmod +x ~/.ssh_askpass
        
        # Add the private key to the agent using the passphrase
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' | DISPLAY=None SSH_ASKPASS=~/.ssh_askpass ssh-add - >/dev/null
        
        # Debug: Check if the key is added to the agent
        ssh-add -l

    - name: Add SiteGround to known_hosts
      run: |
        # Add the host to known_hosts to avoid host key verification error
        mkdir -p ~/.ssh
        ssh-keyscan -p ${{ secrets.SG_PORT }} ${{ secrets.SG_HOST }} >> ~/.ssh/known_hosts

    - name: SSH into SiteGround and pull latest code
      run: |
        # Debug: Check SSH connection
        ssh -v -p ${{ secrets.SG_PORT }} ${{ secrets.SG_USER }}@${{ secrets.SG_HOST }} "echo 'SSH connection successful'"
        
        # SSH into the server and pull the latest code
        ssh -p ${{ secrets.SG_PORT }} ${{ secrets.SG_USER }}@${{ secrets.SG_HOST }} "cd www/api.shop.lakeshorelabradoodles.com/public_html && git pull origin main"
