name: Deploy to SiteGround

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Setup SSH with a passphrase
      env:
        SSH_PASSPHRASE: ${{secrets.SG_PASSWORD}}
        SSH_PRIVATE_KEY: ${{secrets.SG_SSH_PRIVATE_KEY}}
      run: |
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        echo "echo $SSH_PASSPHRASE" > ~/.ssh_askpass && chmod +x ~/.ssh_askpass
        echo "$SSH_PRIVATE_KEY" | tr -d '\r' | DISPLAY=None SSH_ASKPASS=~/.ssh_askpass ssh-add - >/dev/null
    
    - name: SSH into SiteGround and pull latest code
      run: |
        ssh -p ${{ secrets.SG_PORT }} ${{ secrets.SG_USER }}@${{ secrets.SG_HOST }} "cd www/api.shop.lakeshorelabradoodles.com/public_html && git pull origin main"
